root: true
extends:
  - eslint:recommended
  - google
  - plugin:prettier/recommended
plugins:
  - import
  - prettier
env:
  browser: false
  node: true
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2017
  sourceType: module
globals:
  PRODUCTION: readonly
