# Shared Folders
folders:
  input: src
  output: public
  includes: _components
  layouts: _layouts

# Static Asset Folders
assets:
  images: images
  videos: videos
  fonts: fonts

# JavaScript Input/Output Config
#   output: input
#     output - Output file (no extension)
#     input - Input file (with extension) from folders.source
javascript:
  esm:
    js/main: js/main.js
  iife:
    test/iffe: iffe.js

# Sass Config
sass:
  src: sass/**/*.scss
  dest: css
  lint: true
  config:
    outputStyle: compressed

# Service Worker Config
serviceWorker:
  src: sw.js
  dest: sw.js
  pattern:
    - css/**/*.css
    - js/**/*.js
    - index.html

# Manifest config
manifest:
  src: manifest.json
  dest: manifest.json

# HTML Optimization
optimize:
  critical:
    inline: true
    minify: true
  htmlmin:
    collapseWhitespace: true
    sortAttributes: true
    sortClassNames: true
